name = "alexsinfarosa"
type = "javascript"
account_id = "1442179bab093913e938bfd19778f224"

# zone_id = "your-zone-id"
routes = ["alexsinfarosa.com/*", "localhost:8788/*"]

kv_namespaces = [
  {binding = "NEWA", id = "1d289899395f4a3c9769daef121782cd"},
  { binding = "Ciccio_KV", id = "88127c24ae224f1f9734d8d427e8982f" }
]
